Abort on failure to install packages
When I tried to use this script on my Intex Aqua Fish today, it failed
to install zypper as follows:

Resolving
Testing changes
Finished                                                       [                               ] (0%)
The following packages have to be installed:
 augeas-libs-1.0.0-1.1.4.armv7hl        Libraries for augeas
 zypper-1.8.3-1.1.38.armv7hl    Command line software manager using libzypp
Proceed with changes? [N/y] y

Installing
Starting
Refreshing software list
Querying
Resolving dependencies
Downloading packages
Finished
Fatal error: File './core/armv7hl/augeas-libs-1.0.0-1.1.4.armv7hl.rpm' not found on medium 'https://releases.jolla.com/releases/2.1.4.14/jolla/armv7hl/'

Nevertheless the script continued to make changes to my device despite
necessary packages might be missing.

These changes exit with exit code above zero if either installing
zypper failed or if installing the new Jolla-C-related packages
failed.